CREATE TABLE job_statuses
(
    id   INT PRIMARY KEY NOT NULL,
    name VARCHAR         not null
);


INSERT INTO job_statuses (id, name)
VALUES (1, 'Queued'),
       (2, 'Progress'),
       (3, 'Failure');

CREATE TABLE projects
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    uuid       UUID      DEFAULT gen_random_uuid(),
    name       VARCHAR                                          NOT NULL,
    url        VARCHAR                                          NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE jobs
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    uuid        UUID                     DEFAULT gen_random_uuid(),
    created_at  TIMESTAMP                DEFAULT CURRENT_TIMESTAMP,
    started_at  TIMESTAMP                DEFAULT NULL,
    finished_at TIMESTAMP                DEFAULT NULL,
    detail      json,
    project_id  INT             not null,
    status_id   INT             not null default 1,
    FOREIGN KEY (status_id) REFERENCES job_statuses (id),
    FOREIGN KEY (project_id) REFERENCES projects (id)
);