-- CREATE TABLE job_statuses
-- (
--     id   INT PRIMARY KEY NOT NULL,
--     name VARCHAR         not null
-- );
--
--
-- INSERT INTO job_statuses (id, name)
-- VALUES (1, 'Queued'),
--        (2, 'Progress'),
--        (3, 'Failure');

CREATE TABLE projects
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    uuid       UUID      DEFAULT gen_random_uuid(),
    name       VARCHAR                                          NOT NULL,
    url        VARCHAR                                          NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO projects (uuid, name, url)
VALUES ('52786323-d7d7-4623-8667-a1879aab0039', 'init project',
        'https://github.com/guardrailsio/backend-engineer-challenge');

CREATE TYPE job_statuses AS ENUM ('Queued', 'InProgress', 'Success', 'Failure');

CREATE TABLE jobs
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    uuid        UUID         DEFAULT gen_random_uuid(),
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    started_at  TIMESTAMP    DEFAULT NULL,
    finished_at TIMESTAMP    DEFAULT NULL,
    detail      json,
    project_id  INT                                              not null,
    status      job_statuses default 'Queued',
    FOREIGN KEY (project_id) REFERENCES projects (id)
);