// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MessagePublisher is an autogenerated mock type for the MessagePublisher type
type MessagePublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, topic, b
func (_m *MessagePublisher) Publish(ctx context.Context, topic string, b []byte) {
	_m.Called(ctx, topic, b)
}

// NewMessagePublisher creates a new instance of MessagePublisher. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMessagePublisher(t testing.TB) *MessagePublisher {
	mock := &MessagePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
