### Create Project
POST http://localhost:8080/api/v1/projects
Content-Type: application/json

{
  "name": "test",
  "url": "https://github.com/guardrailsio/backend-engineer-challenge"
}

### Get all Project
GET http://localhost:8080/api/v1/projects
Accept: application/json

### Update Project by uuid
PUT http://localhost:8080/api/v1/projects/52786323-d7d7-4623-8667-a1879aab0039
Content-Type: application/json

{
  "name": "test 12345",
  "url": "https://github.com/guardrailsio/backend-engineer-challenge"
}

### Get Project with Jobs by uuid
GET http://localhost:8080/api/v1/projects/52786323-d7d7-4623-8667-a1879aab0039
Accept: application/json

### Scan project
POST http://localhost:8080/api/v1/projects/52786323-d7d7-4623-8667-a1879aab0039/scan
Accept: application/json
